### ISSUE TITLE
Duplicated of https://www.npmjs.com/package/libphonenumber-js

### ISSUE THREAD

**Issue by hnq90** [libphonenumbers/libphonenumbers.github.io#1]
I don't know why you created this organization & this repo.
Because there's a [`libphonenumber`](https://www.npmjs.com/package/libphonenumber-js) package which has ported to JavaScript already.

**Comment by Bunlong** [comment]
@hnq90 the above package is expensive (big size: 5.76 MB) and it's a rewrite of Google Android's (not a portal of Google's libphonenumber). The one I created is smaller (1.16 MB) and compatible with both JavaScript and TypeScript (This is what I want for both front-end and back-end).
